# Generated by Django 2.2 on 2022-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(unique=True)),
                ('stu_name', models.TextField()),
                ('Stu_branch', models.TextField()),
                ('stu_ph', models.IntegerField()),
            ],
        ),
    ]
