# Generated by Django 2.2 on 2022-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='stu_id',
        ),
        migrations.AlterField(
            model_name='stu',
            name='stu_ph',
            field=models.TextField(null=True),
        ),
    ]
