# Generated by Django 4.0.4 on 2022-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20220505_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='stu_ph',
            field=models.IntegerField(),
        ),
    ]
